kind: pipeline
type: ssh
name: default

server:
  host: docker.kernelbug.org
  user: flappie
  port: 443
  password:
    from_secret: password

steps:
- name: build
  image: commands
  commands:
  - git clone https://github.com/Naroj/flask-hello.git
  - python3 -m venv /home/flappie/v
  - /home/flappie/v/bin/pip install -r /home/flappie/flask-hello/requirements.txt

trigger:
  branch:
  - master
  event:
  - push


