kind: pipeline
type: ssh
name: default

server:
  host: docker.kernelbug.org
  user: flappie
  password:
    from_secret: password

steps:
  - name: build
    commands:
      - git clone https://github.com/Naroj/flask-hello.git /home/flappie/flask-hello
      - logger "build done"



trigger:
  branch:
  - master
  event:
  - push
