kind: pipeline
type: ssh
name: default

server:
  host: docker.kernelbug.org
  user: flappie
  password:
    from_secret: password

steps:
  - name: build
    commands:
      - rm -rf /home/flappie/flask-hello
      - git clone https://github.com/Naroj/flask-hello.git /home/flappie/flask-hello
      - python3 -m venv /home/flappie/v
      - /home/flappie/v/bin/pip install -r /home/flappie/flask-hello/requirements.txt
      - sudo /bin/systemctl restart flaskie
      - logger "build done"



trigger:
  branch:
  - master
  event:
  - push
