kind: pipeline
type: ssh
name: default

server:
  host: docker.kernelbug.org
  user: flappie
  password:
    from_secret: password

steps:
- name: build
  image: commands
  commands:
  - git clone https://github.com/Naroj/flask-hello.git

trigger:
  branch:
  - master
  event:
  - push
